#define PERMISSIVE_HOLD
/* #define PERMISSIVE_HOLD_PER_KEY */
/* #define HOLD_ON_OTHER_KEY_PRESS */
/* #define HOLD_ON_OTHER_KEY_PRESS_PER_KEY */
/* #define IGNORE_MOD_TAP_INTERRUPT */

#define TAPPING_TERM 200
/* #define QUICK_TAP_TERM */
